### ISSUE TITLE
import error in utils

### ISSUE THREAD

**Issue by gryBox** [stephenhky/PyShortTextCategorization#1]
Hi - I just installed shorttext on my Windows 7 machine (no errors).  However I did get a `ImportError: No module named 'kerasmodel_io'`

![image](https://cloud.githubusercontent.com/assets/16763201/22561417/c08c4338-e93d-11e6-81dd-9295ca64660c.png)

**Comment by stephenhky** [comment]
Thank you for letting me know about this bug. While this bug does not appear on my side, I do think it may be due to relative path issue in various systems. I will branch it with another path, and then you will download it to see if it works for you.

**Comment by stephenhky** [comment]
Hi gryBox,

I just updated my module codes. Would you download my source code from repository, and on the directory, run the following:

`python setup.py install`

**Comment by gryBox** [comment]
@stephenhky  - thanks for the change.  I overlooked the fact that this was made for python 2.x.  I use python 3.x.  Seems like the install is failing here `shorttext\data\data_retrieval.py` 

I wanted to use your package to extract keyword from very short texts i.e definitions (in the tech space) i.e

> 64b/66b encoding. an algorithm for encoding data for transmission in which each 64-bit data word is converted to a 66-bit transmission character. each transmission character is prefixed with either binary "01" or binary "10". this, combined with scrambling, gives the signal desirable engineering properties, yet incurs a much lower overhead than the traditional 8b/10b encoding. 64b/66b encoding. data communication

the output being:

1. algorithm
2. 66-bit transmission character
3.  transmission character
4. data
5 ...

Do you have any suggestions?

**Comment by stephenhky** [comment]
So far my package deals with supervised learning with short text under the lack of information. But for your task, I think a topic model using gensim, with algorithms such as LDA, should be enough. I heard of STM too.

**Comment by AshBT** [comment]
Hey, 
Was able to get the package loaded by switching 
`from utils.<sub_module> import <method/class>`  import statements
to 
`from **shorttext.**utils.<sub_module> import <method/class>` 

and 

`import 'utils.<sub_module>' as <name>`
to 
`import **'shorttext.**utils.<sub_module> as <name>`

Any concerns with this?

**Comment by stephenhky** [comment]
@AshBT did you experience an error?

**Comment by AshBT** [comment]
Yes, I was getting import errors when importing the packages like so:  
"from utils.<sub_module> import ... or import utils.<sub_module> as ... "

So I just changed it to "import shorttext.utils.<submodule> as ... " etc

and it worked...

I'm still testing it out (using the tokenizers and getting the models built), but at this point I'm seriously impressed!  Great work!

I'll let you know if I have any other issues.

**Comment by stephenhky** [comment]
@AshBT Thanks for pointing it out. Yes, including "shorttext" at the beginning of the imports is essential. I probably have to improve my tutorial...

Thanks for trying it out!

**Comment by stephenhky** [comment]
@AshBT I have overlooked your point, and I believe I now truly understand your solution.
