### ISSUE TITLE
Will there ever be Python 3 support?

### ISSUE THREAD

**Issue by justinas-kazanavicius** [stephenhky/PyShortTextCategorization#11]
Will there ever be Python 3 support?

**Comment by stephenhky** [comment]
Thanks for asking. This is part of the plan to make `shorttext1 to support Python 3.

**Comment by nmstoker** [comment]
Any indication of where the main challenges are too switching to Python 3?

Is it something someone could do for themselves with a short-term personal fork or is it more of a large scale undertaking?

**Comment by stephenhky** [comment]
most of the codes are not python 2 specific. the most obvious is `print` statements, which there are not a lot. There are some built-in functions that output a list in Python 2, but an iterator in Python 3, which may require some careful. I do not see it as complicated, but it takes careful steps that the whole package can be compatible with both.

**Comment by nmstoker** [comment]
Thanks Stephen!

I started to have a go myself [here](/nmstoker/PyShortTextCategorization) with use of [futurize](http://python-future.org/automatic_conversion.html).

Also, as the stemming module needed a tiny change to make it Python 3 compatible, for now I've forked it [here](/nmstoker/stemming) and am then just installing locally to replace my copy of the PyPI version.

**Comment by stephenhky** [comment]
Thanks, nmstoker!
nice to know some more packages.

If you are doing it for the whole package, i would like to let you know that the PyPI version and the current Github version has some differences, because the one on github is about to be dispatched as release 0.4.0. If you want to work on it, it might be better to work on the github version.

**Comment by nmstoker** [comment]
Thanks Stephen. Good to know re: the github version; I was using that version, so all good there.

Still plenty to do but am chipping away at the task and a few parts of your excellent tutorial now work

**Comment by stephenhky** [comment]
Thanks! I am close to the point of publishing 0.4.0. I do not know how long the Python 3 coding will take (but I do not think it can be done within a very short time), so I will publish 0.4.0 without python 3 support. But whenever you completed it, I will ask Chinmaya to modify the travis file for testing before merging. And then there will be a new release that contains your updates.

**Comment by stephenhky** [comment]
How is the progress?

**Comment by Sandy4321** [comment]
yes it would be great make it works on python 3 , thanks

**Comment by nmstoker** [comment]
Sorry, I haven't been able to do much for a while but I'm keen to take a look this coming weekend.

**Comment by stephenhky** [comment]
I am submitting a pull request to your branch, because there are new commits.

**Comment by stephenhky** [comment]
I have opened a branch called [py3test](https://github.com/stephenhky/PyShortTextCategorization/tree/py3test), to test the modification and its compatibility with Python 3.

Currently the stemming is Python-2 only. I made some changes to some simple stuff, e.g., the `print` statement.

**Comment by stephenhky** [comment]
Right now, the branch [py3test](https://github.com/stephenhky/PyShortTextCategorization/tree/py3test) passes all the existing unit tests.

However, I will still need to test the stacking and the retrieval of NIH data.

If you spot any errors regarding Python 3.5 and 3.6 in the codes of this branch, feel free to submit a pull request!

**Comment by stephenhky** [comment]
I have removed some further bugs in the project, and they are all in the branch [py3test](https://github.com/stephenhky/PyShortTextCategorization/tree/py3test). I will make a pull request to the master branch in a few hours. And maybe for another 24 hours, I will publish version 1.0.0 with Python 3.5 and 3.6 compatible package.

**Comment by stephenhky** [comment]
I have merged it to the master branch, and will tag this version. Feel free to try and run it on Python 3.5 and 3.6. I will later this week officially make it 1.0.0 if there is no big bugs found.
