### ISSUE TITLE
jaccardscore_sents

### ISSUE THREAD

**Issue by peterjmayhew** [stephenhky/PyShortTextCategorization#114]
Running the following code should yield a result of 0.64. 

```
from shorttext.utils import load_word2vec_model

wvmodel = load_word2vec_model('/path/to/model_file.bin')

from shorttext.metrics.embedfuzzy import jaccardscore_sents

jaccardscore_sents('doctor', 'physician', wvmodel)
```

But results in a error message 

> ***** TypeError: object of type 'filter' has no len()**

**Comment by stephenhky** [comment]
Addressed in https://github.com/stephenhky/PyShortTextCategorization/pull/115 .

**Comment by stephenhky** [comment]
Release 1.4.5 is available: https://github.com/stephenhky/PyShortTextCategorization/releases/tag/1.4.5
Updated version of `shorttext` can be installed through `pip` with the fix.

**Comment by peterjmayhew** [comment]
Thanks, I confirm the problem is resolved.
