### ISSUE TITLE
Importing problem (not installation) over google colab

### ISSUE THREAD

**Issue by yomnamahmoud** [stephenhky/PyShortTextCategorization#123]
I am experimenting with the library for the first time. The installation was successful and didn't need any extra steps. however when I started importing the library I got the following error related to keras:

/usr/local/lib/python3.7/dist-packages/shorttext/generators/bow/AutoEncodingTopicModeling.py in <module>()
      8 from gensim.corpora import Dictionary
      9 from keras import Input
---> 10 from keras.engine import Model
     11 from keras.layers import Dense
     12 from scipy.spatial.distance import cosine

ImportError: cannot import name 'Model' from 'keras.engine' (/usr/local/lib/python3.7/dist-packages/keras/engine/__init__.py)

I tried to install keras separately but no improvement. any suggestions would be appreciated.

**Comment by stephenhky** [comment]
I have no problem when doing this locally. Do you have more details about your environment?

**Comment by yomnamahmoud** [comment]
I am working on Google colab (its a virtual cloud environment) https://colab.research.google.com/

 Python 3 as a runtime . I read in the FAQ that people had problem with installation on the colab environment but I didn't face any of these issues . It just appeared in the importing.

**Comment by WilburMercer** [comment]
I had the same issue in Colab. I don't know if that affects anything else, but changing "from keras.engine import Model" to "from keras import Model" in "shorttext/generators/bow/AutoEncodingTopicModeling.py" seems to let me import the module.

**Comment by stephenhky** [comment]
@WilburMercer Oh thanks for the suggestion. Will update.

**Comment by yomnamahmoud** [comment]
@WilburMercer Worked perfectly! Thanks for the suggestion!

**Comment by stephenhky** [comment]
partially addressed in https://github.com/stephenhky/PyShortTextCategorization/pull/124
But will need to change all `keras` to `tf.keras` to completely remove the problem
