### ISSUE TITLE
Remove negation terms from stopwords.txt

### ISSUE THREAD

**Issue by star1327p** [stephenhky/PyShortTextCategorization#127]
I noticed that [stopwords.txt](https://github.com/stephenhky/PyShortTextCategorization/blob/master/shorttext/utils/stopwords.txt)  includes negation terms such as "no" and "not". These terms revert the meaning of a word or a sentence, so they should be preserved in the text data. For example, "not a good idea" would become "good idea" after stopword removal. Therefore, I recommend removing negation terms from the stopword list. Thanks!

**Comment by stephenhky** [comment]
The list of stopwords is actually from NLTK, and I believe those negated words are there because they existed in some other languages.

I may include a new subroutine to handle this so that other developers can reproduce their result with previous versions of the codes.

**Comment by star1327p** [comment]
Thank you for explaining! Looking forward to your new subroutine.

**Comment by stephenhky** [comment]
Update in progress, as shown in the pull request: https://github.com/stephenhky/PyShortTextCategorization/pull/128

**Comment by stephenhky** [comment]
I will merge the pull request in this week.

**Comment by stephenhky** [comment]
`shorttext` 1.5.4 is released, with this pull request merged.
