### ISSUE TITLE
extend score to take an array of shorttext

### ISSUE THREAD

**Issue by rja172** [stephenhky/PyShortTextCategorization#131]
Currently, score takes only a single input and as a result, the method is very slow if you are trying to classify thousands of examples. Is there a way you can generate scores for 10K+ samples at the same time.

**Comment by stephenhky** [comment]
vectorizing the input might works....

**Comment by rja172** [comment]
do you have an example?

**Comment by rja172** [comment]
As suggested, vectorizing `np. vectorize(self.classifier.score)(data['X'])` did help speed up the process. However, inference is still very slow. I think if the internal functions can handle multiple shorttext at the same time might significantly help speed up things.

**Comment by stephenhky** [comment]
Because the procedure involves tokenizing the string, it takes some time. Yes, doing it in parallel can speed it up. I will need to do some careful changes to the codes.

**Comment by ragrawal** [comment]
this PR addresses it: https://github.com/stephenhky/PyShortTextCategorization/pull/134

**Comment by stephenhky** [comment]
Release 1.5.6.
