### ISSUE TITLE
Small typo with training data function "inaugual" (missing "r")

### ISSUE THREAD

**Issue by nmstoker** [stephenhky/PyShortTextCategorization#14]
There's a small typo in the function name "inaugual" (it's missing an "r"), _ie it should be **inaugural**_, as per the tutorial: https://pythonhosted.org/shorttext/tutorial_dataprep.html#example-training-data-3-inaugural-addresses )

This search should show where it's referenced (comes up twice):
https://github.com/stephenhky/PyShortTextCategorization/search?utf8=%E2%9C%93&q=inaugual&type=

**Comment by stephenhky** [comment]
Thanks for pointing it out. I fixed the typo, and keep the typo in the import for backward compatibility.
