### ISSUE TITLE
multiple contents

### ISSUE THREAD

**Issue by chocosando** [stephenhky/PyShortTextCategorization#20]
Hi. Thank you for your nice library shorttext. 

I'm trying to read my own data .csv file consisted of one subject and three contents (three columns).

e.g. 
subject,  content1,  content2,  content3
... 

But I failed. 
Can I use multiple columns of contents? 

Thank you.

**Comment by stephenhky** [comment]
Thank you for the question. Right now, it only takes one column of content.

Would putting all these columns in different rows work for your case?

**Comment by chocosando** [comment]
Thank you for reply.
Yes I'd like to use several columns. 

S1, C11, C12, C13
S2, C21, C22, C23
S3, C31, C32, C33

...

In this version (one content column), is it be Ok ? 

S1, C11
S1, C12
S1, C13
S2, C21
S2, C22
S2, C23
S3, C31
S3, C32
S3, C33
...




Thank you.

**Comment by stephenhky** [comment]
Yes, it will be okay.

I will consider multiple column content in data retrieval.

**Comment by chocosando** [comment]
Thank you.
I appreciate it. :-)
