### ISSUE TITLE
tensorboard,

### ISSUE THREAD

**Issue by chocosando** [stephenhky/PyShortTextCategorization#21]
Hi again.

1. tensor board,
I need to use tensorboard, where is log file ? How can I see the log file location ? 

2. training,
I'd like to improve my model by modulating parameters. 
The default epoch is 10. Can I change it ?
And can i change the training steps ? 

Thank you.
Best regards,

**Comment by chocosando** [comment]
regarding epoch number, I found it : the third argument is number. Thank you.

**Comment by stephenhky** [comment]
Since we are using `keras`, to use tensorboard, you can use this function in `keras` as documented: https://keras.io/callbacks/#tensorboard

Yes, you can change the number of epochs, and I am glad you found it. :)

**Comment by chocosando** [comment]
Thank you for reply.
I'll try  according to that link. 
Thank you.
