### ISSUE TITLE
reference or citation ?

### ISSUE THREAD

**Issue by chocosando** [stephenhky/PyShortTextCategorization#22]
Dear, 
I'd like to do research by using this PyShortTextCategorization.

1. Is there some references to cite ? or brief explanations of this library. 

2. What should I do when I write a paper ?
Is there any references which I should cite ? 
Or some sentences for Acknowledgement ? 

Thank you.

**Comment by stephenhky** [comment]
Thank you for using shorttext, and for your question. I do not have a particular paper for this package. However, if you use any particular functions or class, check out the docstring. If there is a paper (or papers) mentioned, cite those papers. For example, if you use `CNNWordEmbed` in https://github.com/stephenhky/PyShortTextCategorization/blob/master/shorttext/classifiers/embed/nnlib/frameworks.py, according to the docstring, cite: Yoon Kim, "Convolutional Neural Networks for Sentence Classification," *EMNLP* 2014, 1746-1751 (arXiv:1408.5882)

On the other hand, look at the documentation for the reference too: [http://shorttext.readthedocs.io/](http://shorttext.readthedocs.io/)

**Comment by stephenhky** [comment]
I have updated my documentation to include a simple guideline for citation.
