### ISSUE TITLE
standalone ?

### ISSUE THREAD

**Issue by chocosando** [stephenhky/PyShortTextCategorization#23]
Hi. 
I have many questions.... :-)  

I'm a beginner for python.
Is there any method to run the code standalone ? 

e.g. I trained my data. And I'd like to see the scores on terminal by classifier.score('apple') . The word 'apple' can be changed.

Thank you
regards,

**Comment by stephenhky** [comment]
Yes, you can run scripts to achieve this purpose. Refer to `ShortTextCategorizerConsole` in http://shorttext.readthedocs.io/en/latest/scripts.html . You can go to the `/bin` folder to see how it was implemented in Python.

But if you need a GUI, one needs to use wxPython or something comparable, which I did not provide.

**Comment by chocosando** [comment]
Hi. Thank you for reply. 
I do not need a GUI. Running in Terminal as a command is better. :- )

1. Error. 
I'm trying to run ShortTextCategozierConsole . But I got an error :  ImportError: cannot import name compactmodel_io . 

2.  Where is input argument ?   Arguments are some confusing.
I'm trying like this : 

ShortTextCategorizerModelTrainer /demo5280.bin ~/Downloads/GoogleNews-vectors-negative300.bin 

( --wv is not working.  ).
( demo5280.bin  is  trained model from classifier.save_compact_model ) 


Would you help me ?

Thank you so much !!

**Comment by stephenhky** [comment]
1. For the error you encountered, would you show me the stack trace of the error message?

2. The argument you put is correct.

If it is a bug, I will need to fix it and make a new release.

**Comment by chocosando** [comment]
Thank you for reply. 

The error is below:

Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/bin/ShortTextCategorizerConsole", line 24, in <module>
    import shorttext
  File "/usr/local/lib/python2.7/dist-packages/shorttext/__init__.py", line 9, in <module>
    from . import classifiers
  File "/usr/local/lib/python2.7/dist-packages/shorttext/classifiers/__init__.py", line 7, in <module>
    from .bow.topic.LatentTopicModeling import GensimTopicModeler, LDAModeler, LSIModeler, RPModeler
  File "/usr/local/lib/python2.7/dist-packages/shorttext/classifiers/bow/__init__.py", line 1, in <module>
    from . import topic
  File "/usr/local/lib/python2.7/dist-packages/shorttext/classifiers/bow/topic/__init__.py", line 1, in <module>
    from . import LatentTopicModeling
  File "/usr/local/lib/python2.7/dist-packages/shorttext/classifiers/bow/topic/LatentTopicModeling.py", line 4, in <module>
    from shorttext.generators.bow.GensimTopicModeling import gensim_topic_model_dict
  File "/usr/local/lib/python2.7/dist-packages/shorttext/generators/__init__.py", line 1, in <module>
    from .bow.GensimTopicModeling import load_gensimtopicmodel
  File "/usr/local/lib/python2.7/dist-packages/shorttext/generators/bow/__init__.py", line 1, in <module>
    from . import AutoEncodingTopicModeling
  File "/usr/local/lib/python2.7/dist-packages/shorttext/generators/bow/AutoEncodingTopicModeling.py", line 13, in <module>
    from utils import compactmodel_io as cio, classification_exceptions as e, kerasmodel_io as kerasio, \
ImportError: cannot import name compactmodel_io

**Comment by chocosando** [comment]
One more question regarding arguments:

one argument is trained model, and second is wv model.
Where is input text ? 

Thank you.

**Comment by stephenhky** [comment]
Thanks for the stack trace.

For the argument, I made a mistake when answering you.... before putting the wv model, put `--wv` in the argument.

After it runs, it will show you prompt asking you to input text.

I am working on the bug fixing

**Comment by stephenhky** [comment]
BTW, thanks for bringing up this. I discovered that there is another bug associated with this, about the size of vectors. We have changed the default length of vectors, but it didn't reflect in the script, which will cause problem during run time.

**Comment by stephenhky** [comment]
sorry for the delayed response. would you uninstall shorttext by

```
>>> pip uninstall shorttext
```

and then reinstall it from the github:

```
>>> pip install -U git+https://github.com/stephenhky/PyShortTextCategorization@master
```

(you might need to add `sudo` in front of these two commands.)

see if your problems are solved.

**Comment by chocosando** [comment]
I really appreciate it.
Sorry to delayed response. I'm in out of my office because of small workshop. 
When I return to my office, I'll try again according to your guide. I really excited to run the code : ) 
Thank you again. 
Sincerely,

**Comment by stephenhky** [comment]
Understandable. I was not focused on this because of the long weekend, and it took me a while what the chain of problems are. Let me know how it goes when you have time.

**Comment by chocosando** [comment]
Hi. 

1. 
I just tried to run the code : 

$ ShortTextCategorizerConsole  /demo5280.bin   # demo5280.bin is trained data from classifier.save_compact_model.   

( Is that correct ?  : $ ShortTextCategorizerConsole  /demo5280.bin  ) 

Results are below: 
Using TensorFlow backend.
Retrieving classifier name...
Traceback (most recent call last):
  File "/usr/local/bin/ShortTextCategorizerConsole", line 45, in <module>
    raise Word2VecModelNotExistException(args.wv)
shorttext.utils.classification_exceptions.Word2VecModelNotExistException


2. Where is input word ? 
Like classifier.score('artificial intelligence') , simple adding 'artificial intelligence' is not working. 
( $ ShortTextCategorizerConsole  /demo5280.bin  'artificial intelligence' ) 

Thank you.

**Comment by stephenhky** [comment]
For the first question, you need to do add the word2vec model, like this:

```
>>> ShortTextCategorizerConsole /demo5280.bin --wv /path/to/wvmodel.bin
```

For the second question, it will be something like after you run the scripts above, you will enter an interactive mode, where you can input whatever phrase you want to test on. Or if you want to do it programmatically, you have to refer to this tutorial: http://shorttext.readthedocs.io/en/latest/tutorial_nnlib.html#wrapper-for-neural-networks-for-word-embedding-vectors

**Comment by stephenhky** [comment]
I published a new release. See if it solves your problem.

**Comment by chocosando** [comment]
Thank you. 0.5.3 version is not working for me. I'm re-trying with 0.5.4 . Thank you.

**Comment by stephenhky** [comment]
In 0.5.4, I fixed some vecsize problem. Hopefully it works for you now.

**Comment by chocosando** [comment]
I tried to run just before. 
The prompt "Text>" was successfully seen.

After input text for testing, error occurred : 

Traceback (most recent call last):
  File "/usr/local/bin/ShortTextCategorizerConsole", line 67, in <module>
    scoredict = classifier.score(shorttext)
  File "/usr/local/lib/python2.7/dist-packages/shorttext/classifiers/embed/nnlib/VarNNEmbedVecClassification.py", line 280, in score
    matrix = np.array([self.shorttext_to_matrix(shorttext)])
  File "/usr/local/lib/python2.7/dist-packages/shorttext/classifiers/embed/nnlib/VarNNEmbedVecClassification.py", line 243, in shorttext_to_matrix
    matrix[i] = self.word_to_embedvec(tokens[i])
ValueError: could not broadcast input array from shape (300) into shape (100)


Would you help me ? Is there anything I did not check ?

Thank you.

**Comment by stephenhky** [comment]
I think the problem might be the vector size. Try put this into command line:
```
>>> ShortTextCategorizerConsole /demo5280.bin --wv /path/to/wvmodel.bin --vecsize 300
```

**Comment by chocosando** [comment]
Hello. Sorry for delayed reply.
According to suggestion, it works ! Thank you so much. 

ps. it would be better to run like this :    >>>ShortTextCategorizerConsole /demo5280.bin --wv /path/to/wvmodel.bin --vecsize 300 --inputtext "hello shorttext"

**Comment by stephenhky** [comment]
Sure. I can include this option!

**Comment by stephenhky** [comment]
@chocosando release 0.5.5 is out. you can do --inputtext in the command line :)
