### ISSUE TITLE
Integration - Starspace embed all things!

### ISSUE THREAD

**Issue by nsankar** [stephenhky/PyShortTextCategorization#25]
It might be a good idea to integrate the recently released Facebook Starspace with Shorttext. I think there is a good complementary synergy.

https://arxiv.org/abs/1709.03856
https://github.com/facebookresearch/StarSpace

**Comment by stephenhky** [comment]
Thanks @nsankar . I will actively pursue this.

**Comment by stephenhky** [comment]
I will not integrate StarSpace. However, I have included the implementation of Facebook FastText in the recent release (0.5.8). It is similar to Word2Vec.
