### ISSUE TITLE
unexpected keyword argument 'toweight'

### ISSUE THREAD

**Issue by dbonner** [stephenhky/PyShortTextCategorization#26]
I was going through the tutorial on [](http://shorttext.readthedocs.io/en/latest/tutorial_topic.html).
Under "Topic Models in gensim ..." it says that you can to not weigh items you specify (toweight=False).  I can't get this to work with GensimTopicModeler or AutoencodingTopicModeler.  
Command:
topicmodeler3 = shorttext.generators.GensimTopicModeler(toweight=False)
Error:
TypeError                                 Traceback (most recent call last)
<ipython-input-38-4ff5f959d8a3> in <module>()
----> 1 topicmodeler3 = shorttext.generators.GensimTopicModeler(toweight=False)
TypeError: __init__() got an unexpected keyword argument 'toweight'

Command:
autoencoder3 = shorttext.generators.AutoencodingTopicModeler(toweight=False)
Error:
TypeError                                 Traceback (most recent call last)
<ipython-input-37-d11efe83d96c> in <module>()
----> 1 autoencoder3 = shorttext.generators.AutoencodingTopicModeler(toweight=False)
TypeError: __init__() got an unexpected keyword argument 'toweight'

I'm using:
Ubuntu 17.10
Python 2.7.14 (virtual environment)
TensorFlow 1.4rc1
Keras 2.0.8

**Comment by stephenhky** [comment]
Thanks for pointing out. It is a typo. Please change `toweight=` to `toweigh=`. I will correct the tutorial accordingly.

**Comment by dbonner** [comment]
Hi,
The topicmodeller works:
topicmodeler3 = shorttext.generators.GensimTopicModeler(toweigh=False)
However there is still an error with autoencoders:
autoencoder3 = shorttext.generators.AutoencodingTopicModeler(toweigh=False)
Error:

TypeError                                 Traceback (most recent call
last)<ipython-input-4-2f77e316d66d> in <module>()----> 1 autoencoder3
= shorttext.generators.AutoencodingTopicModeler(toweigh=False)
TypeError: __init__() got an unexpected keyword argument 'toweigh'

Cheers,
Daniel

*Dr Daniel Bonner*
Lecturer, ANU Medical School, The Canberra Hospital, ACT 02 6244 3500
Psychiatrist, Brian Hennessy Rehabilitation Centre, Haydon Drive, Bruce,
ACT 02 6205 1222

**Comment by stephenhky** [comment]
Oh, the class `AutoencodintTopicModeler` does not have the parameter `toweigh` in the constructor.

**Comment by stephenhky** [comment]
btw, i have tried `64` in tensorflow in two different macbook pro, and i have not encountered the error.
