### ISSUE TITLE
AttributeError - can't save model

### ISSUE THREAD

**Issue by dbonner** [stephenhky/PyShortTextCategorization#27]
I tried the command:
classifier.save_compact_model('sublda8nb.bin')
I get this error:
AttributeError                            Traceback (most recent call last)
<ipython-input-36-ccdc47d6887c> in <module>()
----> 1 classifier.save_compact_model('sublda8nb.bin')

/home/daniel/vcuda27/local/lib/python2.7/site-packages/shorttext/classifiers/bow/topic/SkLearnClassification.pyc in save_compact_model(self, name)
    159         :type name: str
    160         """
--> 161         topicmodel_info = self.topicmodeler.get_info()
    162         cio.save_compact_model(name, self.savemodel, 'topic_sklearn',
    163                                topicmodel_info['suffices']+['.pkl'],

AttributeError: GensimTopicModeler instance has no attribute 'get_info'

**Comment by stephenhky** [comment]
GensimTopicModeler do not have a dressed wrapper. That's why there is an error. Would you give me the whole flow since when you start the classifier to see what is going on?

**Comment by dbonner** [comment]
subtopicmodeler = shorttext.generators.GensimTopicModeler()
subtopicmodeler.train(subdict, 8)
from sklearn.naive_bayes import GaussianNB
classifier = shorttext.classifiers.TopicVectorSkLearnClassifier(subtopicmodeler, GaussianNB())
classifier.train(subdict)
classifier.score('functional integral')
classifier.save_compact_model('sublda8nb.bin')
Error:
AttributeError                            Traceback (most recent call last)
<ipython-input-28-ccdc47d6887c> in <module>()
----> 1 classifier.save_compact_model('sublda8nb.bin')

/home/daniel/vcuda27/local/lib/python2.7/site-packages/shorttext/classifiers/bow/topic/SkLearnClassification.pyc in save_compact_model(self, name)
    159         :type name: str
    160         """
--> 161         topicmodel_info = self.topicmodeler.get_info()
    162         cio.save_compact_model(name, self.savemodel, 'topic_sklearn',
    163                                topicmodel_info['suffices']+['.pkl'],

AttributeError: GensimTopicModeler instance has no attribute 'get_info'

**Comment by stephenhky** [comment]
my bad on the tutorial. Try `LDAModeler`, `LSIModeler` and `RPModeler`, and see if it works. If it does, I will update my tutorial accordingly again.
(Sorry my tutorial has been misleading.)

**Comment by stephenhky** [comment]
I verified it works. I updated the documentation too.
