### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by kenyeung128** [stephenhky/PyShortTextCategorization#3]
Hi, I got the following error when i import shorttext, how shall i resolve?

Using TensorFlow backend.

I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.7.5 locally
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/shorttext/__init__.py", line 7, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/shorttext/utils/__init__.py", line 3, in <module>
    from . import gensim_corpora
  File "/usr/local/lib/python2.7/dist-packages/shorttext/utils/gensim_corpora.py", line 2, in <module>
    from .textpreprocessing import spacy_tokenize as tokenize
  File "/usr/local/lib/python2.7/dist-packages/shorttext/utils/textpreprocessing.py", line 5, in <module>
    import spacy
  File "/usr/local/lib/python2.7/dist-packages/spacy/__init__.py", line 8, in <module>
    from . import en, de, zh, es, it, hu, fr, pt, nl, sv, fi, bn, he
  File "/usr/local/lib/python2.7/dist-packages/spacy/en/__init__.py", line 4, in <module>
    from ..language import Language
  File "/usr/local/lib/python2.7/dist-packages/spacy/language.py", line 12, in <module>
    from .syntax.parser import get_templates
ImportError: dlopen: cannot load any more object with static TLS

**Comment by stephenhky** [comment]
It looks like it is a spaCy issue. It requires the most updated spaCy. Is yours the most updated one? Let me know if you can successfully import the library after you reinstall. It may be on the side of the package.

**Comment by kenyeung128** [comment]
yes, i used latest version of spaCy 1.8.1, and get this error

**Comment by stephenhky** [comment]
How about running this in terminal?

`python -m spacy download en`

After downloading the library, try to import the package again.

**Comment by kenyeung128** [comment]
it doesn't help, as i have used the english model already.

but i have found a workaround, I need to do this.

import spacy
import shorttext

then it works

**Comment by stephenhky** [comment]
Hi Ken... Thanks for letting me know. I think I need some time to figure out what was going on.

**Comment by stephenhky** [comment]
What is your version of Tensorflow?

**Comment by stephenhky** [comment]
I changed my backend between Tensorflow and Theano, and I do not have the problem that you posted. I am using Python 2.7. I am running on macOS Sierra.

I googled online that it looks like previous version of tensorflow would give rise to this problem. Mine is pretty new (not sure if it is the newest). I am not sure if that could be the case.

**Comment by stephenhky** [comment]
It looks like it is not a bug, but a configuration error regarding the numerical libraries. spaCy makes use of CV2, which causes this problem.

The Github of Tensorflow talked about this problem: https://github.com/tensorflow/models/issues/523
And it cited this thread in StackOverflow: http://stackoverflow.com/questions/19268293/matlab-error-cannot-open-with-static-tls

The way to do it is to reload the library, or reinstall Tensorflow etc. To work around, load opencv2, or spaCy first before loading the library.
