### ISSUE TITLE
TSNE graph ? 

### ISSUE THREAD

**Issue by chocosando** [stephenhky/PyShortTextCategorization#31]
Hello,

Thank you for your ShortText. 
Can I make graph of grouping of the "subjects" like TSNE ? 

Thank you.

**Comment by stephenhky** [comment]
I do not build in TSNE. But if you did some unsupervised learning on the subjects, you can definitely visualize the embeddings using tSNE

**Comment by chocosando** [comment]
Thank you for reply.
Thank you again.
