### ISSUE TITLE
from shorttext.classifiers import MaxEntClassifier is it regression?

### ISSUE THREAD

**Issue by Sandy4321** [stephenhky/PyShortTextCategorization#35]
seems to be maxent is a fancy word for regression or you do have something special in your maxent?
https://www.quora.com/What-is-the-relationship-between-Log-Linear-model-MaxEnt-model-and-Logistic-Regression
or
https://en.wikipedia.org/wiki/Multinomial_logistic_regression
```
Multinomial logistic regression is known by a variety of other names, including polytomous LR,[2][3] multiclass LR, softmax regression, multinomial logit, the maximum entropy (MaxEnt) classifier, and the conditional maximum entropy model.[4]
```

**Comment by Sandy4321** [comment]
http://www.logos.ic.i.u-tokyo.ac.jp/~tsuruoka/maxent/
maximum entropy classifiers (also known as "multinomial logistic regression")

**Comment by stephenhky** [comment]
Yes, it is logistic regression, except that the activation function is softmax instead of sigmoid.

**Comment by stephenhky** [comment]
References:

- https://web.stanford.edu/class/cs124/lec/Maximum_Entropy_Classifiers.pdf
- https://dl.acm.org/citation.cfm?id=234289
- http://www.kamalnigam.com/papers/maxent-ijcaiws99.pdf

**Comment by Sandy4321** [comment]
great thanks, but do you have several pages description, pls

**Comment by stephenhky** [comment]
These slides may be helpful: https://web.stanford.edu/class/cs124/lec/Maximum_Entropy_Classifiers.pdf
