### ISSUE TITLE
Input to shorttext.generators.LDAModeler()

### ISSUE THREAD

**Issue by malizad** [stephenhky/PyShortTextCategorization#46]
I was wondering what should be the format of data as input for: 

shorttext.generators.LDAModeler() 
topicmodeler.train(data, 100)

Can I feed it with a pandas column? Or it should be in a dictionary format? If a dictionary, what should be the keys? I have a large set of tweets.

**Comment by stephenhky** [comment]
You can refer to the details [here](https://shorttext.readthedocs.io/en/latest/tutorial_dataprep.html).

Basically, `data` is a dictionary, with the keys of the labels, and the values beings lists of strings.

**Comment by malizad** [comment]
Thanks.
So does it mean that first I have to apply a topic modeler on my raw data to obtain a set of topics (labels as you said) and their associated words, and then used that as input to topicmodeler.train(data, 100)?

**Comment by stephenhky** [comment]
No need, you just need to directly put the `data` (as a dictionary) to `topicmodeler.train(data, 100)`. In the training process, each class labels will be seen as a document in usual topic modeling publication. The purpose of this is to find the topics associated with each class labels.

If you want to do pure topic modeling, I would suggest you use `gensim`. The topic modeler in `shorttext` wraps those in `gensim`, but serves a different purpose. You can refer to the publication list found [here](https://shorttext.readthedocs.io/en/latest/tutorial_topic.html#topic-models-in-gensim-lda-lsi-and-random-projections).

**Comment by malizad** [comment]
Many thanks.
But usually topic modelers accept a document-word matrix. In all of your examples, you've used datasets that the key is related to its corresponding values. So I was wondering, in case of a large tweet dataset for example, how should I organize the data into a dictionary. Should I use userid as key and put all of her tweets as its value?

**Comment by stephenhky** [comment]
In that case, you can make a dictionary, with keys being automated numbers, and the values being lists of strings in the documents.

After you got a topic model, you can represent the lists of words using the topic vector output by the topic model.

BTW, you gave me an idea what to add to `shorttext`.
