### ISSUE TITLE
StackedGeneralization error

### ISSUE THREAD

**Issue by jperkins909** [stephenhky/PyShortTextCategorization#5]
import shorttext

  File "..\site-packages\shorttext\stack\__init__.py", line 1, in <module>
    from stacking import StackedGeneralization, LogisticStackedGeneralization
ImportError: cannot import name 'StackedGeneralization'

  File "..\site-packages\shorttext\stack\__init__.py", line 1, in <module>
    from stacking import LogisticStackedGeneralization
ImportError: cannot import name 'LogisticStackedGeneralization'

**Comment by stephenhky** [comment]
I have no problem importing the package. Would you tell me your OS, python version, shorttext version, and the whole error message?

**Comment by stephenhky** [comment]
Actually, I believe I saw the possible cause of this error, which can happen to some systems with specific path name config. I updated a line to consider a general situation. Would you uninstall `shorttext`, and re-install the most updated version of this repository by:

`>>> pip install -U git+https://github.com/stephenhky/PyShortTextCategorization@master`
?

Let me know if you see any error messages.

**Comment by stephenhky** [comment]
A new release was just published today. Hopefully this solve the bugs. Let me know if you still encounter the problem. Or if you know what the problem exactly is, feel free to submit a pull request.

**Comment by stephenhky** [comment]
Do you still see this problem? I just recently published another release (0.3.6)
