### ISSUE TITLE
load shorttext without tensorflow

### ISSUE THREAD

**Issue by miketrimmel** [stephenhky/PyShortTextCategorization#65]
Hey, I have a problem running shorttext library at the computing cluster of my university because of tensorflow and the "historical" cpu´s my university is running.

When loading shorttext I get the error:

2019-04-09 18:29:19.243146: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.

For my problem I don´t need the tensorflow library. So my question is. Is there a possibility to load shorttext without tensorflow? Or is there a fix for this during the installation procedure?

Thanks in advance, best mike

**Comment by stephenhky** [comment]
Is it that you already installed `shorttext`? If yes, and if you want to avoid installing `TensorFlow`, try installing Theano instead. And before login in Python, make the backend to Theano by running in the console: `switch_kerasbackend theano` .

**Comment by miketrimmel** [comment]
Thank you very much for the hint. I resoved it the way to switch to theano before loading shorttext library in my python script as proposed here:

https://stackoverflow.com/questions/42660871/changing-keras-backend-to-theano-in-ipython-notebook

It´s working now.

**Comment by stephenhky** [comment]
Great to hear that!
