### ISSUE TITLE
missing variable in tutorial

### ISSUE THREAD

**Issue by az0** [stephenhky/PyShortTextCategorization#70]
In  this tutorial
https://shorttext.readthedocs.io/en/latest/tutorial_charbaseseq2seq.html

On this line
`seq2seqer = shorttext.generators.CharBasedSeq2SeqGenerator(chartovec_encoder, latent_dim, 120)`

The variable `latent_dim` is undefined

**Comment by stephenhky** [comment]
Thanks! Updated.
