### ISSUE TITLE
Data nihreports not available anymore

### ISSUE THREAD

**Issue by AlessandroVol23** [stephenhky/PyShortTextCategorization#72]
Some datasets are not available anymore. 

For example the following:
`nihtraindata = shorttext.data.nihreports(sample_size=None)` 

Error message:
```
Downloading...
Source:  http://storage.googleapis.com/pyshorttext/nih_grant_public/nih_full.csv.zip
Failure to download file!
(<class 'urllib.error.HTTPError'>, <HTTPError 404: 'Not Found'>, <traceback object at 0x7f09063ed788>)
```

Python error:
```
HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:
```

When opening the link the same error appears:

![image](https://user-images.githubusercontent.com/19362086/65425840-44b37c80-de0f-11e9-9887-f97dbeb6fa99.png)

**Comment by stephenhky** [comment]
Thanks for submitting the issue. This is happening for all datasets because the old bucket is no longer working.

I am finding a new place for the datasets and I will publish a new release.

**Comment by AlessandroVol23** [comment]
Perfect thanks! Do you have a link to the mentioned dataset? Because I'd need it for a tutorial at the moment . A small sample would be more then enough. Unfortunately I can't find it online at the moment. 

Thanks! :-)

**Comment by stephenhky** [comment]
Release 1.1.5 has been published for the fix.
