### ISSUE TITLE
Module Not Found: spell.edits1_comb when trying to import local repository

### ISSUE THREAD

**Issue by AlessandroVol23** [stephenhky/PyShortTextCategorization#76]
Hi,

I try to make some local changes on your repository but I get an error when I try to import it:

Error: 
```python
ModuleNotFoundError: No module named 'PyShortTextCategorization.shorttext.spell.edits1_comb'
```

I've installed all dependencies by executing `setup.py` from the root directory.
It runs successfully but I still get the error message. 

## Reproduce

1. `git clone https://github.com/stephenhky/PyShortTextCategorization.git /tmp/TEST_PYSHORT`
2. `cd /tmp/`
3. `sudo chmod +x TEST_PYSHORT/setup.px`
4. Executing the script from my conda environment: `sudo /home/xxx/anaconda3/envs/xxx/bin/python setup.py install` 
5. Using the cloned module in python:
```python
import sys
sys.path.append('.')
from TEST_PYSHORT import shorttext
```
6. Error:
```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-fc636292b55b> in <module>
----> 1 from TEST_PYSHORT import shorttext

/tmp/TEST_PYSHORT/shorttext/__init__.py in <module>
      5 from . import generators
      6 from . import stack
----> 7 from .smartload import smartload_compact_model
      8 from . import metrics
      9 from . import spell

/tmp/TEST_PYSHORT/shorttext/smartload.py in <module>
      9 from .classifiers import load_autoencoder_topic_sklearnclassifier, load_gensim_topicvec_sklearnclassifier
     10 from .classifiers import load_maxent_classifier
---> 11 from .spell import loadSCRNNSpellCorrector
     12
     13

/tmp/TEST_PYSHORT/shorttext/spell/__init__.py in <module>
      2 from .basespellcorrector import SpellCorrector
      3
----> 4 from .norvig import NorvigSpellCorrector
      5 from .sakaguchi import SCRNNSpellCorrector, loadSCRNNSpellCorrector
      6

/tmp/TEST_PYSHORT/shorttext/spell/norvig.py in <module>
      6
      7 from . import SpellCorrector
----> 8 from .editor import compute_set_edits1, compute_set_edits2
      9
     10

/tmp/TEST_PYSHORT/shorttext/spell/editor.py in <module>
      1
----> 2 from .edits1_comb import edits1_comb
      3
      4
      5 def compute_set_edits1(word):

ModuleNotFoundError: No module named 'TEST_PYSHORT.shorttext.spell.edits1_comb'
```

I am not sure if I am doing something wrong here with installing the dependencies or if there is an actual error.

Thanks for your help :-)

**Comment by stephenhky** [comment]
Never try to import the package this way. All the module paths are written assuming `shorttext` as a package.If you import it as something within `TEST_PYSHORT`, unexpected errors emerge.

If you want to make modifications to the package and test it, you can do it in one of the following ways:

1. Write a lot of unit tests.
2. Use virtualenv.
3. Install the package using `pip install -e .` so that the package is in sync with your modifications.
