### ISSUE TITLE
VarNNSumEmbedVecClassifier classdict error 

### ISSUE THREAD

**Issue by glinert** [stephenhky/PyShortTextCategorization#8]
Not sure if this is my error, it probably is to be honest, but it seems that the method which turns classdicts into vector space is creating arrays of arrays which then can't be fed into the neural net train  function.

array([ array([  2.55833234e-02,  -8.17019377e-03,   2.01286003e-02,
          1.17644003e-01,  -4.52266509e-02,   3.94913053e-02,
          8.78725506e-02,  -7.59354832e-02,   3.08374938e-02,
          2.19436490e-03,  -1.22635821e-04,  -6.92241929e-02,
         -1.23372407e-02,  -1.01080711e-02,  -1.19589722e-01,
          9.89894749e-02,   5.00888270e-02,   8.93359533e-02,

etc. 

So it receives a 1d array accidentally.

Anyway, I love your package otherwise. 

-Steven

**Comment by stephenhky** [comment]
Hi Steven,

Would you tell me how you get this error message in detail? Which codes did you input? etc.

Stephen

**Comment by glinert** [comment]
ValueError: Error when checking input: expected conv1d_1_input to have 3 dimensions, but got array with shape (55993, 1)

for when you try:

mynn.train(classdict,fr.CNNWordEmbed(nb_labels=7))

I tried changing your code to 
`        embedvecs = []
        for classlabel in classlabels:
            for shorttext in classdict[classlabel]:
                embedvec = np.sum(np.array([self.word_to_embedvec(token) for token in spacy_tokenize(shorttext)]),
                                  axis=0)
                embedvec = np.reshape(embedvec, embedvec.shape+(1,)
                embedvec /= np.linalg.norm(embedvec)
                embedvecs.append(embedvec)
                category_bucket = [0]*len(classlabels)
                category_bucket[lblidx_dict[classlabel]] = 1
                indices.append(category_bucket)

        indices = np.array(indices)
        embedvecs = np.array(embedvecs)
        return classlabels, embedvecs, indices`

that is, adding embedvec = np.reshape(embedvec, embedvec.shape+(1,))

but that didn't work...

**Comment by glinert** [comment]
sorry that message came out messy.

Do you want to contact me on email at glinert@pivotusventures.com?

I'd love to get this fixed with you.

-Steven

**Comment by stephenhky** [comment]
bug fixed, released as 0.3.7.
