### ISSUE TITLE
scikit-learn 0.23 not supported

### ISSUE THREAD

**Issue by Dobatymo** [stephenhky/PyShortTextCategorization#93]
The requirements should either set `scikit-learn<0.23` or the code needs to be updated.
The first error is with `from sklearn.external import joblib`. `import joblib` is preferred now.

**Comment by stephenhky** [comment]
It is addressed in the PR 94: https://github.com/stephenhky/PyShortTextCategorization/pull/94

**Comment by stephenhky** [comment]
Addressed in the release: https://github.com/stephenhky/PyShortTextCategorization/releases/tag/1.2.4
