### ISSUE TITLE
Deep Neural Networks with Word-Embedding problem 

### ISSUE THREAD

**Issue by bekirbostanci** [stephenhky/PyShortTextCategorization#96]
I faced this problem

kmodel = shorttext.classifiers.frameworks.CNNWordEmbed(len(trainclassdict.keys()), vecsize=300)
classifier = shorttext.classifiers.VarNNEmbeddedVecClassifier(wvmodel)
classifier.score('artificial intelligence')
 

ModelNotTrainedException                  Traceback (most recent call last)
<ipython-input-22-f0aaa6c7518d> in <module>()
      2 
      3 classifier = shorttext.classifiers.VarNNEmbeddedVecClassifier(wvmodel)
----> 4 classifier.score('artificial intelligence')
      5 

/usr/local/lib/python3.6/dist-packages/shorttext/classifiers/embed/nnlib/VarNNEmbedVecClassification.py in score(self, shorttext)
    224         """
    225         if not self.trained:
--> 226             raise e.ModelNotTrainedException()
    227 
    228         # retrieve vector

**Comment by stephenhky** [comment]
You didn't train the model. You have to train the model first, so that `ModelNotTrainedException` would not be raised.

Reference: https://shorttext.readthedocs.io/en/latest/tutorial_nnlib.html#wrapper-for-neural-networks-for-word-embedding-vectors

**Comment by bekirbostanci** [comment]
thank you so much I missed out that line
