### ISSUE TITLE
AttributeError: type object 'FastText' has no attribute 'load_facebook_vectors

### ISSUE THREAD

**Issue by Dobatymo** [stephenhky/PyShortTextCategorization#97]
```
  File "shorttext\utils\wordembed.py", line 33, in load_fasttext_model
    return gensim.models.FastText.load_facebook_vectors(path)
AttributeError: type object 'FastText' has no attribute 'load_facebook_vectors'
```

It should be called `gensim.models.fasttext.load_facebook_vectors` (lowercase)

Using shorttext-1.2.4 and gensim-3.8.3

**Comment by stephenhky** [comment]
THanks.... there are some versioning bugs with using gensim code here. Will update

**Comment by stephenhky** [comment]
This merged PR has addressed this issue: https://github.com/stephenhky/PyShortTextCategorization/pull/98

**Comment by stephenhky** [comment]
Release 1.2.5: https://github.com/stephenhky/PyShortTextCategorization/releases/tag/1.2.5
